---
- name: Install and start NGINX
  hosts: web
  become: true
  become_method: sudo
  become_user: root

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Start and enable nginx
      service:
        name: nginx
        state: started
        enabled: yes


